# Generated by Django 5.2.17 on 2026-08-26 18:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Toyota Corolla 2022', max_length=100)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_period', models.CharField(choices=[('/day', 'Per day'), ('/week', 'Per week'), ('/month', 'Per month')], default='/week', max_length=10)),
                ('badge', models.CharField(blank=True, help_text="Optional label, e.g. 'New' or 'Popular'", max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('is_available', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, help_text='Tick once someone on the team has followed up')),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not shown to the applicant')),
            ],
            options={
                'verbose_name': 'Driver lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now, help_text='Date the offer was submitted / preferred registration date')),
                ('offer_type', models.CharField(choices=[('sell', 'Sell the car'), ('rent', 'Rent it out through Taxi Partner')], max_length=10)),
                ('car_brand', models.CharField(max_length=60)),
                ('car_model', models.CharField(max_length=60)),
                ('car_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)])),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False, help_text='Tick once someone on the team has followed up')),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not shown to the applicant')),
            ],
            options={
                'verbose_name': 'Investor lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
